# Generated by Django 5.0.6 on 2026-05-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
