# Generated by Django 5.0.6 on 2026-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankInterface', '0002_account_daily_limit_account_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ifsc_code',
            field=models.CharField(default='DKGB0000001', max_length=11),
        ),
    ]
